name: Lab 2 CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install profiling tools
        run: |
          sudo apt-get update
          sudo apt-get install -y linux-tools-common linux-tools-generic sysstat ltrace strace procps

      - name: Install Zig 0.13.0
        run: |
          wget https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz
          tar -xf zig-linux-x86_64-0.13.0.tar.xz
          sudo mv zig-linux-x86_64-0.13.0 /usr/local/zig
          # Add /usr/local/zig to the PATH for subsequent steps
          echo "/usr/local/zig" >> $GITHUB_PATH

      - name: Run tests
        run: zig build test

      - name: Run profiling
        run: zig build profile --release=fast -Dprofiles-data-dir=profiling/data -Dprofiling-processes=1,2,4

      - name: Upload profiling data artifact
        uses: actions/upload-artifact@v3
        with:
          name: profiling-data
          path: profiling/data
